// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_js_bridge/test/typescript/ts_definitions_cli_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_js_bridge/src/typescript/ts_definitions_generator.dart'
    as _i2;
import 'package:flutter_js_bridge/src/typescript/ts_definitions_models.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TSDefinitionsGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockTSDefinitionsGenerator extends _i1.Mock
    implements _i2.TSDefinitionsGenerator {
  MockTSDefinitionsGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateBaseInterface() =>
      (super.noSuchMethod(
            Invocation.method(#generateBaseInterface, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateBaseInterface, []),
            ),
          )
          as String);

  @override
  String generateActionsDefinitions(List<_i4.TSActionDefinition>? actions) =>
      (super.noSuchMethod(
            Invocation.method(#generateActionsDefinitions, [actions]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateActionsDefinitions, [actions]),
            ),
          )
          as String);

  @override
  String generateInterfaceDefinitions(
    List<_i4.TSInterfaceDefinition>? interfaces,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateInterfaceDefinitions, [interfaces]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateInterfaceDefinitions, [interfaces]),
            ),
          )
          as String);

  @override
  String generateDefinitionFile({
    List<_i4.TSInterfaceDefinition>? interfaces = const [],
    List<_i4.TSActionDefinition>? actions = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateDefinitionFile, [], {
              #interfaces: interfaces,
              #actions: actions,
            }),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateDefinitionFile, [], {
                #interfaces: interfaces,
                #actions: actions,
              }),
            ),
          )
          as String);

  @override
  String generateFromRegisteredHandlers(
    Map<String, dynamic>? registeredHandlers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateFromRegisteredHandlers, [
              registeredHandlers,
            ]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateFromRegisteredHandlers, [
                registeredHandlers,
              ]),
            ),
          )
          as String);

  @override
  _i5.Future<void> writeDefinitionFile(
    String? path, {
    List<_i4.TSInterfaceDefinition>? interfaces = const [],
    List<_i4.TSActionDefinition>? actions = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeDefinitionFile,
              [path],
              {#interfaces: interfaces, #actions: actions},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
