name: Flutter Tests

# Note: You can run the same checks locally before pushing using:
# Windows: scripts/pre_push_check.bat
# macOS/Linux: scripts/pre_push_check.sh

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Dart SDK first
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.7.2'
      
      # Then set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'
          channel: 'stable'
      
      # Verify installed versions
      - name: Verify Dart and Flutter versions
        run: |
          dart --version
          flutter --version
      
      # Update Flutter
      - name: Update Flutter
        run: flutter upgrade
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Format code
        run: dart format .
      
      - name: Analyze project source
        run: flutter analyze --exclude=cli_tester
      
      - name: Run tests
        run: flutter test
